version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
    # ports:
    #   - 3000:3000
    restart: always
    deploy:
      replicas: 3
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
      - httpd
    ports:
      - '3001:88'
      - '3002:80'
    restart: always
  httpd:
    image: httpd
    ports:
      - '99:80'

