version: "3"
services:
  db:
    hostname: db
    image: postgres:13
    ports:
      - '5555:5432'
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
  srv:
    build:
      context: .
      dockerfile: odoo.Dockerfile
    depends_on:
      - db
    restart: always
  proxy:
    image: nginx
    depends_on:
      - srv
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d/
    ports:
      - '80:80'
    # restart: always

      


